import { useState } from 'react';
import { ShieldCheck, LogOut, FileText, Headphones, UserRound } from 'lucide-react';
import type { Snapshot } from '../domain/types';
import { command, supabase } from '../lib/api';
import { Button, Notice, RowLink } from '../components/ui';

export function Account({ snapshot, refresh, onTerms, onSafety, onMfa }: { snapshot: Snapshot; refresh: () => Promise<void>; onTerms: () => void; onSafety: () => void; onMfa: () => void }) {
  const [busy, setBusy] = useState(false), [message, setMessage] = useState('');
  return <div className="account-grid"><section className="panel"><div className="profile-heading"><span className="avatar large"><UserRound size={32} /></span><div><h2>{snapshot.profile.full_name}</h2><span className="small-tag">{snapshot.profile.role === 'driver' ? 'MOTOCICLISTA' : snapshot.profile.role === 'admin' ? 'ADMINISTRAÇÃO' : 'PASSAGEIRO'}</span></div></div><form className="form-stack" onSubmit={async event => { event.preventDefault(); const form = new FormData(event.currentTarget); setBusy(true); try { await command('update_profile', { full_name: form.get('full_name'), phone: form.get('phone') }); await refresh(); setMessage('Dados atualizados.'); } catch (error) { setMessage((error as Error).message); } finally { setBusy(false); } }}><label>Nome completo<input name="full_name" defaultValue={snapshot.profile.full_name} minLength={3} maxLength={100} required autoComplete="name" /></label><label>Celular com DDD<input name="phone" defaultValue={snapshot.profile.phone} type="tel" minLength={10} maxLength={20} required autoComplete="tel" /></label><Button busy={busy}>Salvar dados</Button></form>{message ? <Notice>{message}</Notice> : null}</section><section className="panel account-links"><RowLink icon={<ShieldCheck size={22} />} title="Autenticação em duas etapas" detail="Proteja o acesso à sua conta" onClick={onMfa} /><RowLink icon={<Headphones size={22} />} title="Ajuda e segurança" detail="Ocorrências, privacidade e exclusão de conta" onClick={onSafety} /><RowLink icon={<FileText size={22} />} title="Regras e privacidade" detail={`Versão ${snapshot.settings.terms_version}`} onClick={onTerms} /><Button variant="secondary" onClick={async () => { const { error } = await supabase.auth.signOut(); if (error) setMessage(error.message); }}><LogOut size={18} />Sair da conta</Button><p className="helper">MotoJá · versão 0.2.0</p></section></div>;
}
