import { useState } from 'react';
import { PilotReadiness } from './PilotReadiness';
import { Bike, CircleAlert, Wallet, ShieldCheck, ExternalLink, UsersRound } from 'lucide-react';
import { command, supabase } from '../lib/api';
import type { Snapshot } from '../domain/types';
import { money, statusLabels } from '../domain/rides';
import { Button, Empty, Modal, Notice } from '../components/ui';

export function Admin({ snapshot, refresh }: { snapshot: Snapshot; refresh: () => Promise<void> }) {
  const [section, setSection] = useState('overview'), [busy, setBusy] = useState(false), [message, setMessage] = useState('');
  const [review, setReview] = useState<{ driver: string; status: string } | null>(null), [note, setNote] = useState('');
  const [resolve, setResolve] = useState<string | null>(null), [fileUrl, setFileUrl] = useState('');
  const admin = snapshot.admin;
  if (!admin) return <Notice error>Confirme a autenticação em duas etapas para acessar a administração.</Notice>;
  async function act(action: string, payload: Record<string, unknown>) { setBusy(true); setMessage(''); try { await command(action, payload); await refresh(); setReview(null); setResolve(null); setNote(''); } catch (error) { setMessage((error as Error).message); } finally { setBusy(false); } }
  const active = admin.rides.filter(ride => !['completed', 'cancelled'].includes(ride.status));
  return <div className="admin-workspace"><div className="page-heading"><p className="eyebrow">ADMINISTRAÇÃO</p><h1>Uma cidade em movimento.</h1><p>Controle de cadastros, viagens e atendimento.</p></div><div className="admin-tabs">{[['overview', 'Visão geral'], ['drivers', 'Motociclistas'], ['support', 'Atendimento'], ['operation', 'Operação']].map(([id, label]) => <button key={id} aria-pressed={section === id} onClick={() => setSection(id)}>{label}</button>)}</div>
    {message ? <Notice error>{message}</Notice> : null}
    {section === 'overview' ? <><div className="metrics admin-metrics"><article><Bike size={22} /><small>Corridas em andamento</small><strong>{active.length}</strong></article><article><UsersRound size={22} /><small>Motociclistas cadastrados</small><strong>{admin.drivers.length}</strong></article><article><CircleAlert size={22} /><small>Chamados abertos</small><strong>{admin.incidents.filter(item => item.status !== 'resolved').length}</strong></article><article><Wallet size={22} /><small>Valor das concluídas</small><strong>{money(admin.rides.filter(ride => ride.status === 'completed').reduce((total, ride) => total + ride.price_cents, 0))}</strong></article></div><section className="panel"><h2>Corridas recentes</h2><p className="helper">Até 100 corridas recentes. Valores de viagem não representam receita da plataforma.</p>{admin.rides.length ? <div className="table-scroll"><table><thead><tr><th>Destino</th><th>Situação</th><th>Valor</th><th>Data</th></tr></thead><tbody>{admin.rides.map(ride => <tr key={ride.id}><td>{ride.destination.label}</td><td>{statusLabels[ride.status]}</td><td>{money(ride.price_cents)}</td><td>{new Date(ride.requested_at).toLocaleDateString('pt-BR')}</td></tr>)}</tbody></table></div> : <Empty title="As primeiras corridas aparecem aqui">A operação continua fechada até a preparação do piloto.</Empty>}</section></> : null}
    {section === 'drivers' ? <div className="admin-driver-list">{admin.drivers.length ? admin.drivers.map(driver => <article className="panel" key={driver.user_id}><div className="section-title"><div><h2>{driver.full_name}</h2><p>{driver.model || 'Moto ainda não cadastrada'} · {driver.plate || 'Sem placa'}</p></div><span className="small-tag">{driver.approval_status === 'approved' ? 'APROVADO' : driver.approval_status === 'suspended' ? 'SUSPENSO' : 'EM ANÁLISE'}</span></div><p className="helper">Conta: {driver.user_id}</p><div className="document-list">{driver.documents.map(document => <div className="admin-document" key={document.id}><span>{({ identity: 'Identidade', license: 'CNH', vehicle: 'Veículo', permit: 'Autorização', insurance: 'Seguro' } as Record<string, string>)[document.kind]}<small>Validade: {document.expires_on} · {document.status}</small></span><button className="text-button" onClick={async () => { setFileUrl(''); const { data, error } = await supabase.storage.from('motoja-documents').createSignedUrl(document.object_path, 60); if (error) setMessage(error.message); else setFileUrl(data.signedUrl); }}><ExternalLink size={17} />Ver arquivo</button><button className="text-button" disabled={busy} onClick={() => act('review_document', { document_id: document.id, status: 'approved' })}>Aprovar</button><button className="text-button danger-text" disabled={busy} onClick={() => act('review_document', { document_id: document.id, status: 'rejected' })}>Rejeitar</button></div>)}</div><div className="button-row"><Button variant="secondary" onClick={() => { setReview({ driver: driver.user_id, status: 'approved' }); setNote(''); }}>Aprovar cadastro</Button><Button variant="secondary" onClick={() => { setReview({ driver: driver.user_id, status: 'suspended' }); setNote(''); }}>Suspender</Button></div></article>) : <Empty title="Nenhum motociclista cadastrado">Os novos cadastros aparecerão aqui para sua análise.</Empty>}{fileUrl ? <Notice><a href={fileUrl} target="_blank" rel="noreferrer">Abrir documento privado — link válido por 60 segundos</a></Notice> : null}</div> : null}
    {section === 'support' ? <section className="panel"><h2>Solicitações e ocorrências</h2>{admin.incidents.length ? admin.incidents.map(incident => <article className="incident-row" key={incident.id}><span className="small-tag">{incident.status === 'resolved' ? 'RESOLVIDO' : 'ABERTO'} · {incident.category}</span><p>{incident.description}</p><small>{new Date(incident.created_at).toLocaleString('pt-BR')} · {incident.id}</small>{incident.status !== 'resolved' ? <Button variant="secondary" onClick={() => { setResolve(incident.id); setNote(''); }}>Registrar atendimento</Button> : null}</article>) : <Empty title="Nenhuma solicitação por enquanto">Relatos de segurança e pedidos de privacidade serão listados aqui.</Empty>}</section> : null}
    {section === 'operation' ? <><PilotReadiness /><div className="account-grid"><section className="panel"><h2>Preparação da operação</h2><form className="form-stack" onSubmit={event => { event.preventDefault(); const form = new FormData(event.currentTarget); const fees = Object.fromEntries(['base_cents', 'minimum_cents', 'per_km_cents', 'per_minute_cents'].map(key => [key, Math.round(Number(form.get(key)) * 100)])); void act('settings', { ...fees, mode: form.get('mode'), support_phone: form.get('support_phone'), support_email: form.get('support_email') }); }}><label>Disponibilidade<select name="mode" defaultValue={snapshot.settings.mode}><option value="closed">Fechado — em preparação</option><option value="pilot">Piloto — apenas convidados</option></select></label><div className="form-columns">{[['base_cents', 'Bandeirada (R$)'], ['minimum_cents', 'Mínimo (R$)'], ['per_km_cents', 'Por km (R$)'], ['per_minute_cents', 'Por minuto (R$)']].map(([key, label]) => <label key={key}>{label}<input type="number" name={key} step="0.01" min="0" max="500" required defaultValue={Number(snapshot.settings[key as keyof typeof snapshot.settings]) / 100} /></label>)}</div><label>Telefone do suporte<input name="support_phone" type="tel" defaultValue={snapshot.settings.support_phone} maxLength={20} /></label><label>E-mail do suporte<input name="support_email" type="email" defaultValue={snapshot.settings.support_email} /></label><Button busy={busy}>Salvar configuração</Button></form></section><section className="panel"><ShieldCheck size={28} /><h2>Antes de abrir ao público</h2><p>Confirme o enquadramento municipal, documentação da empresa, seguro para a atividade e atendimento aos usuários.</p><p>O piloto requer participantes convidados e motociclistas aprovados. Novos cadastros não ganham acesso às corridas automaticamente.</p><form className="form-stack" onSubmit={event => { event.preventDefault(); const form = new FormData(event.currentTarget); void act('set_tester', { user_id: form.get('user_id'), enabled: form.get('enabled') === 'yes' }); }}><label>ID da conta participante<input name="user_id" required pattern="[0-9a-fA-F-]{36}" placeholder="ID exibido no cadastro" /></label><label>Acesso ao piloto<select name="enabled"><option value="yes">Convidar participante</option><option value="no">Remover acesso</option></select></label><Button variant="secondary" busy={busy}>Atualizar convite</Button></form></section></div></> : null}
    {review ? <Modal title={review.status === 'approved' ? 'Aprovar motociclista' : 'Suspender cadastro'} onClose={() => setReview(null)}><p>A aprovação exige documentos analisados e dentro da validade. Registre o resultado da verificação.</p><form className="form-stack" onSubmit={event => { event.preventDefault(); void act('review_driver', { driver_id: review.driver, status: review.status, note }); }}><label>Justificativa<textarea value={note} onChange={event => setNote(event.target.value)} minLength={10} maxLength={1000} required /></label><Button busy={busy}>Confirmar análise</Button></form>{message ? <Notice error>{message}</Notice> : null}</Modal> : null}
    {resolve ? <Modal title="Registrar atendimento" onClose={() => setResolve(null)}><form className="form-stack" onSubmit={event => { event.preventDefault(); void act('resolve_incident', { incident_id: resolve, resolution: note }); }}><label>Como a solicitação foi atendida?<textarea value={note} onChange={event => setNote(event.target.value)} minLength={10} maxLength={2000} required /></label><Button busy={busy}>Salvar atendimento</Button></form>{message ? <Notice error>{message}</Notice> : null}</Modal> : null}
  </div>;
}
