import { useState } from 'react';
import { Phone, ShieldCheck, HeartPulse, FileText, LockKeyhole, CheckCircle2 } from 'lucide-react';
import { Button, Notice } from '../components/ui';
import { command } from '../lib/api';
import type { Settings } from '../domain/types';

export function Safety({ settings, rideId, signedIn }: { settings: Settings | null; rideId?: string; signedIn: boolean }) {
  const [busy, setBusy] = useState(false), [message, setMessage] = useState(''), [protocol, setProtocol] = useState('');
  return <div className="safety-center"><div className="safety-intro"><ShieldCheck size={30} /><h3>Seu cuidado vem primeiro.</h3><p>Em risco imediato, vá para um local seguro e ligue para o serviço de emergência.</p></div><div className="emergency-grid"><a href="tel:190"><Phone size={24} /><strong>190</strong><span>Polícia Militar</span></a><a href="tel:192"><HeartPulse size={24} /><strong>192</strong><span>SAMU</span></a></div><p className="helper">Os botões abrem o telefone. O MotoJá não aciona os serviços de emergência automaticamente.</p><div className="safety-guidance"><p><CheckCircle2 size={18} />Confira nome, placa e moto antes de embarcar.</p><p><CheckCircle2 size={18} />Use capacete afivelado durante todo o trajeto.</p><p><CheckCircle2 size={18} />Se algo parecer inseguro, não embarque.</p></div>
    <h3>Falar com o MotoJá</h3>{settings?.support_phone ? <a className="button secondary" href={`tel:${settings.support_phone.replace(/[^+\d]/g, '')}`}><Phone size={18} />Ligar para o suporte</a> : <p className="helper">O atendimento telefônico ainda está em configuração. Não há central 24 horas anunciada nesta versão.</p>}
    {signedIn ? <form className="form-stack" onSubmit={async event => { event.preventDefault(); setBusy(true); setMessage(''); const form = new FormData(event.currentTarget); try { const result = await command<{ id: string }>('incident', { ride_id: rideId || null, category: form.get('category'), description: form.get('description') }); setProtocol(result.id); } catch (error) { setMessage((error as Error).message); } finally { setBusy(false); } }}><label>Como podemos ajudar?<select name="category"><option value="safety">Situação de segurança</option><option value="behavior">Conduta de passageiro ou motorista</option><option value="payment">Pagamento</option><option value="support">Outro problema</option><option value="privacy">Meus dados e privacidade</option><option value="delete_account">Solicitar exclusão da minha conta</option></select></label><label>Descreva o que aconteceu<textarea name="description" minLength={10} maxLength={2000} required rows={4} placeholder="Relate os fatos para que possamos analisar." /></label><p className="helper">A ocorrência será registrada para análise. Não envie senhas, dados de cartão ou acusações sem explicar os fatos.</p><Button busy={busy}><FileText size={18} />Registrar solicitação</Button></form> : <p className="helper">Entre na sua conta para registrar e acompanhar uma solicitação.</p>}
    {protocol ? <Notice>Solicitação registrada. Protocolo: {protocol}. O registro não significa que o atendimento já começou.</Notice> : null}{message ? <Notice error>{message}</Notice> : null}
  </div>;
}

export function Terms({ version, onAccepted }: { version: string; onAccepted?: () => Promise<void> }) {
  const [busy, setBusy] = useState(false), [checked, setChecked] = useState(false), [error, setError] = useState('');
  return <div className="legal-copy"><span className="small-tag">PILOTO CONTROLADO · {version}</span><h3>Regras de uso e privacidade</h3><p>Esta versão serve à validação com participantes convidados. A operação pública depende de autorização aplicável, seguro e revisão dos documentos definitivos da empresa.</p><h4>Durante a corrida</h4><p>Use sua própria conta, informe dados corretos, confira a moto e use capacete. É proibido usar o serviço para atividades ilícitas, transportar objetos perigosos ou assediar pessoas. Não transporte encomendas desacompanhadas nesta versão.</p><h4>Se houver um problema</h4><p>Você pode cancelar antes de embarcar, relatar uma ocorrência e contestar pagamentos. Relatos passam por análise; não são prova automática de uma infração. Estas regras não afastam direitos do consumidor nem responsabilidades previstas em lei.</p><h4>Dados tratados</h4><p>O sistema utiliza cadastro, informações da corrida, localização durante a disponibilidade ou viagem, documentos do motociclista e registros de atendimento. O acesso é restrito conforme a função. Links de acompanhamento só funcionam durante a corrida e expiram em até duas horas.</p><h4>Pagamento e atendimento</h4><p>O pagamento é feito diretamente ao motociclista, em dinheiro ou Pix. A confirmação no aplicativo é um registro manual e não comprova transferência bancária. O piloto não oferece atendimento emergencial próprio.</p><h4>Seus direitos</h4><p>Solicite acesso, correção ou exclusão dos seus dados na central de ajuda. Prazos de retenção, identificação do controlador, canal de privacidade e bases legais precisam constar na política definitiva antes do lançamento público.</p><div className="safety-note"><LockKeyhole size={22} /><p>Dados de documentos e corridas não são publicados no perfil público.</p></div>
    {onAccepted ? <><label className="checkbox"><input type="checkbox" checked={checked} onChange={event => setChecked(event.target.checked)} />Li as regras desta versão piloto e estou ciente de suas condições.</label><Button disabled={!checked} busy={busy} onClick={async () => { setBusy(true); try { await command('accept_terms', { version }); await onAccepted(); } catch (error) { setError((error as Error).message); } finally { setBusy(false); } }}>Aceitar regras do piloto</Button>{error ? <Notice error>{error}</Notice> : null}</> : null}
  </div>;
}
